### ISSUE TITLE
paruVendu : scrapping du nombre de pièces

### ISSUE THREAD

**Issue by AldricVS** [M2-CYU-Real-Estate/portal-scrapping-v2#1]
Dans le dernier json du dataset scrappé depuis "paruVendu", je vois qu'on a un problème concernant le nombre de pièces : on récupère le titre.

Exemple : 
```json
"pieces": "Nombre de pièces\n8",
"pieces": "Nombre de pièces\n7",
"pieces": "Nombre de pièces\n3",
```

Le nombre de pièces est bien séparé dans un span à part: 
![image](https://user-images.githubusercontent.com/60403534/229124507-ef182889-88ce-454d-88b5-7f3a9a53e9df.png)

On ne doit donc pas avoir cet élément ici, même si on peut l'enlever par la suite (ce qui serait source d'erreurs)

**Comment by IamDiallo** [comment]
ok je vais corriger ça

**Comment by IamDiallo** [comment]
corriger
