### ISSUE TITLE
paruVendu : référence non trouvée

### ISSUE THREAD

**Issue by AldricVS** [M2-CYU-Real-Estate/portal-scrapping-v2#2]
Je vois plusieurs occurrences (49 pour être exact) de biens sans référence (ça met 0). Pourtant, on a bien une référence.

Exemple : 

```json
{
      "title": "Annonce : Vente Maison Sainte-Terre (33350) 342 m² (2 455 000 €) 992769733501",
      "url": "https://www.paruvendu.fr/immobilier/prestige/maison/propriete-sur-domaine-equestre-avec-deux-gites-proche-st/1267224118A1KIVHMN000",
      "ref": 0,
      "typeBien": "Maison",
      "ville": "Sainte-terre",
      "price": 2455,
      "surface": 342,
      "pieces": "Nombre de pièces\n12",
      "chambres": 0,
      "toilletes": 0,
      "parking": 0,
      "cuisine": "Oui",
}
```

![image](https://user-images.githubusercontent.com/60403534/229125945-161426a0-670f-4c6d-81ac-1c4b0aa5426c.png)

J'en profite pour demander ici pourquoi "cuisine" est à "oui" / "non" et pas à true / false (c'est un booléen)

**Comment by IamDiallo** [comment]
bien vu je corrige aussi

**Comment by IamDiallo** [comment]
résolu.
