### ISSUE TITLE
TOUTES LES SOURCES : Trouver la VRAIE fin de pages

### ISSUE THREAD

**Issue by AldricVS** [M2-CYU-Real-Estate/portal-scrapping-v2#6]
Regarder si on est sur la dernière page pour de vrai.

Par exemple sur ParuVendu : on recherche si le numéro de page courant à la classe "red-border"

Tester en amont à la main (évidemment, dis donc)

**Comment by IamDiallo** [comment]
Corriger. Je vérifie si le button next n'existe plus je considère la page comme étant la dernière page.
